name: Publish
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  push:
    branches:
      - 'master'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      strategy:
        fail-fast: false
        matrix:
          language: [ "javascript" ]
          node: [ "18.x" ]
      steps:
        - name: 🧱 Checkout repository
          uses: actions/checkout@v3
        - name: 🔩 Setup PNPM
          uses: pnpm/action-setup@v2
          with:
            version: latest
        - name: 🔩 Setup Node ${{ matrix.node }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node }}
            registry-url: "https://registry.npmjs.org"
            cache: "pnpm"
        - name: 🚀 Install dependencies
          run: pnpm install
        - name: 🚀 Publish package
          run: pnpm run publish-packages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: 🔩 Setup PNPM
#        uses: pnpm/action-setup@v2
#        with:
#          version: latest
#        - name: 🔩 Setup Node ${{ matrix.node }}
#          uses: actions/setup-node@v3
#          with:
#            node-version: ${{ matrix.node }}
#            registry-url: "https://registry.npmjs.org"
#            cache: "pnpm"
#        - name: 🚀 Install dependencies
#          run: pnpm install
#        - name: 🚀 Publish package
#          run: pnpm run publish-packages
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
