name: Publish
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  push:
    branches:
      - 'master'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org/'
          scope: '@advanced-js'
          auth-token: ${{ secrets.NPM_TOKEN }} # Set your npm token as a secret
      - run: pnpm install --no-frozen-lockfile
      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          echo "Enter your npm username and password"
          echo -n "Username: "
          read npmUsername
          echo -n "Password: "
          read -s npmPassword
          echo -e "\nAuthentication with npm in progress..."
          echo -n "$npmUsername:$npmPassword" | base64 | tr -d '\n' > ~/.npm-auth
          npm 2fa setup -o=2fa
          echo -n "Enter 2FA code: "
          read -s npm2FACode
          echo -e "\nPublishing packages..."
          echo -n "$npm2FACode" | base64 | tr -d '\n' >> ~/.npm-auth
          npm adduser --registry=https://registry.npmjs.org/ --always-auth < ~/.npm-auth
          rm ~/.npm-auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm run release
      - run: pnpm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
